name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploymnet:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@master
      - run: npm ci
      - run: npm run build
      - name: Copying files to server
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_github
          chmod 600 ~/.ssh/id_github
          sshpass -p "${{ secrets.REMOTE_PASSWORD }}" rsync -avzr --delete -e "ssh -i ~/.ssh/id_github -o StrictHostKeyChecking=no" dist/VisitCard/* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PATH }}
          rm ~/.ssh/id_github
